### ISSUE TITLE
Add OIDC Support for Unleash Enterprise Instances

### ISSUE THREAD

**Issue by Adityad92** [Unleash/terraform-provider-unleash#177]
### Describe the feature request

Looks like the current Unleash provider for Terraform does not support authentication with Unleash Enterprise instances that are configured to use OpenID Connect (OIDC). This limits the ability to manage Unleash resources via Terraform for organizations that have implemented OIDC authentication for their Unleash instances.

## Implementation Suggestions
- Add OIDC-specific configuration options to the provider (e.g., client ID, client secret, token URL)
- Implement the OIDC authentication flow to obtain access tokens
- Use the obtained access token for subsequent API calls to Unleash

## Potential Challenges
- Handling token refresh
- Securely managing OIDC credentials in Terraform configurations

### Solution suggestions

Implement OIDC authentication support in the Unleash provider. This would allow users to authenticate with their Unleash Enterprise instances using OIDC credentials instead of relying solely on API tokens.

**Comment by gastonfournier** [comment]
Hi @Adityad92 is this for a self-hosted Unleash or a managed instance? For managed instances, starting on version 6.1.0 (still to be released), this will be configurable via environment variables: https://docs.getunleash.io/how-to/how-to-add-sso-open-id-connect#step-1-setup-required-variables-for-oidc-minimal-setup

For managed instances, because the provider assumes a running instance of Unleash, the environment variables don't make a lot of sense. We have already this need tracked in our backlog but we haven't prioritized it yet. We'll keep this issue updated.

**Comment by Adityad92** [comment]
Hi @gastonfournier. Thanks. We have a self-hosted Unleash instance.

**Comment by gastonfournier** [comment]
This resource was added recently: https://registry.terraform.io/providers/unleash/unleash/latest/docs/resources/oidc
